services:
  api:
    container_name: gd-api
    build:
      dockerfile: Dockerfile.development
      args:
        uid: 1000
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 9113:80
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    networks:
      - backend
    depends_on:
      - database
      - mongo

  database:
    image: postgres:13
    container_name: gd-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  mongo:
    image: mongo:5.0
    container_name: gd-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_MONGO_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
